[dc]
dc01 ansible_host=192.168.57.10

[workstations]
ws01 ansible_host=192.168.57.31

[cheddarsale:children]
dc
workstations

# Settings groups - add hosts here to apply the corresponding role
[no_update]
dc01
ws01

[update]
# add hosts here to enable Windows Update

[disable_defender]

