Set-ADAccountControl -Identity etta.valdez -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity faustino.lawrence -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity betsy.fields -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity katie.sparks -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity tommy.houston -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity deon.robbins -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity augustus.jennings -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity curt.finch -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity francesca.foley -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity iris.black -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity marcus.robinson -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity jerrold.collins -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity moises.tate -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity lindsay.stevens -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity stewart.stephenson -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity eloise.caldwell -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity luz.rivas -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity isaiah.crane -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity caleb.frye -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity willis.blevins -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity aaron.roy -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity charlie.bird -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity homer.ortega -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity mary.medina -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity roderick.alston -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity lorrie.nash -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity marcel.cooley -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity janet.mcbride -DoesNotRequirePreAuth 1
Set-ADAccountControl -Identity dante.valdez -DoesNotRequirePreAuth 1
